const SITE_URL = "https://whoisnnamdi.com";
const EXTRA_ROUTES = [];
const SITEMAP_GENERATED_COMMENT =
  "<!-- Generated by scripts/generate-sitemap.mjs; do not edit by hand. -->";

const buildLastModTag = (value) => {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  return `\n                    <lastmod>${date.toISOString()}</lastmod>`;
};

const createSitemap = (posts) => {
  const latestUpdatedAt = posts.reduce((latest, post) => {
    const candidate = post.updated_at || post.published_at;
    if (!candidate) return latest;
    const candidateDate = new Date(candidate);
    if (Number.isNaN(candidateDate.getTime())) return latest;
    if (!latest) return candidateDate;
    return candidateDate > latest ? candidateDate : latest;
  }, null);

  const rootLastMod = latestUpdatedAt ? latestUpdatedAt.toISOString() : null;

  return `<?xml version="1.0" encoding="UTF-8"?>
    ${SITEMAP_GENERATED_COMMENT}
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>${SITE_URL}</loc>${buildLastModTag(rootLastMod)}
    </url>
    ${posts
      .map(({ slug, updated_at, published_at }) => {
        const lastMod = updated_at || published_at;
        return `
                <url>
                    <loc>${`${SITE_URL}/${slug}/`}</loc>${buildLastModTag(lastMod)}
                </url>
            `;
      })
      .join("")}
    ${EXTRA_ROUTES.map((slug) => {
      return `
                <url>
                    <loc>${`${SITE_URL}/${slug}/`}</loc>${buildLastModTag(rootLastMod)}
                </url>
            `;
    }).join("")}
    </urlset>
`;
};

export {
  SITE_URL,
  EXTRA_ROUTES,
  SITEMAP_GENERATED_COMMENT,
  buildLastModTag,
  createSitemap,
};
